### ISSUE TITLE
VPN tunnel for non-root devices

### ISSUE THREAD

**Issue by dalda123** [zhenyolka/DPITunnel-android#12] opened 2022-07-31 02:42 UTC
DPI tunnel for non-root devices is necessary.

**Comment by zhenyolka** [comment] 2022-07-31 17:12
Duplicate of #7
Always check is there already issue describing your problem.
It's not possible to inject packets without root. VPN Service don't allow it too.

**Closed by zhenyolka** 2022-07-31 17:12 UTC
