### ISSUE TITLE
Maybe this will work with shizuku for non-rooted devices?

### ISSUE THREAD

**Issue by Wjxfi** [zhenyolka/DPITunnel-android#16] opened 2022-09-18 11:39 UTC
https://github.com/RikkaApps/Shizuku

**Comment by zhenyolka** [comment] 2022-09-18 19:31
Duplicate of #7. It is not issue.

**Closed by zhenyolka** 2022-09-18 19:31 UTC

**Comment by zhenyolka** [comment] 2022-09-19 04:26
Shizuku is not replacement for root. Can you understand that raw sockets wont work without real root?

There are many people giving "useful" suggestions how to make it work without root. No one gave real solution yet, you aren't the first.
